import turtle
my_turtle = turtle.Turtle()
turtle.shape("turtle")
turtle.color("blue")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.penup()
turtle.forward(100)
turtle.pendown()

turtle.forward(100)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(60)
turtle.penup()
turtle.forward(100)

turtle.pendown()
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(150)
turtle.forward(173)
turtle.penup()

turtle.left(60)
turtle.forward(100)
turtle.pendown()
turtle.circle(60)



turtle.exitonclick()
